export const hebrew = {
  app: {
    name: 'Reel Rep Training',
    tagline: '',
  },
  
  auth: {
    welcomeBack: 'ברוכים השבים',
    selectRole: 'בחר את התפקיד שלך',
    user: 'משתמש',
    coach: 'מאמן',
    admin: 'מנהל',
    continue: 'המשך',
    signIn: 'התחבר',
    signUp: 'הירשם',
    email: 'אימייל',
    password: 'סיסמה',
    forgotPassword: 'שכחתי סיסמה',
    resetPassword: 'איפוס סיסמה',
    sendResetLink: 'שלח לינק לאיפוס',
    backToLogin: 'חזור להתחברות',
    enterEmail: 'הזן את כתובת האימייל שלך',
    enterPassword: 'הזן את הסיסמה שלך',
    emailSent: 'נשלח אימייל לאיפוס סיסמה',
    signInWithOTP: 'התחבר עם קוד חד פעמי',
    sendOTP: 'שלח קוד',
    enterOTP: 'הזן קוד חד פעמי',
    verify: 'אמת',
    otpSent: 'קוד נשלח לאימייל',
    invalidCredentials: 'אימייל או סיסמה שגויים',
    errorOccurred: 'אירעה שגיאה',
  },
  
  tabs: {
    home: 'בית',
    classes: 'שיעורים',
    shop: 'חנות',
    profile: 'פרופיל',
    admin: 'ניהול',
  },
  
  home: {
    greeting: 'שלום',
    todayWorkout: 'האימון של היום',
    stats: 'סטטיסטיקות',
    workouts: 'אימונים',
    calories: 'קלוריות',
    minutes: 'דקות',
    streak: 'רצף',
    days: 'ימים',
    achievements: 'הישגים',
    quickActions: 'פעולות מהירות',
    logWorkout: 'רשום אימון',
    bookClass: 'הזמן שיעור',
    viewProgress: 'צפה בהתקדמות',
    thisWeek: 'השבוע',
    weeklyGoal: 'יעד שבועי',
    myClasses: 'השיעורים שלי',
    upcomingClasses: 'שיעורים קרובים',
    activeChallenge: 'אתגר פעיל',
  },
  
  classes: {
    upcomingClasses: 'שיעורים קרובים',
    myClasses: 'השיעורים שלי',
    allClasses: 'כל השיעורים',
    book: 'הזמן',
    cancel: 'בטל',
    booked: 'מוזמן',
    full: 'מלא',
    waitlist: 'הרשמה להמתנה',
    spots: 'מקומות',
    spotsLeft: 'מקומות פנויים',
    instructor: 'מאמן',
    duration: 'משך',
    durationMinutes: 'דקות',
    difficulty: 'רמת קושי',
    beginner: 'מתחיל',
    intermediate: 'בינוני',
    advanced: 'מתקדם',
    location: 'מיקום',
    classesUsed: 'שיעורים שנוצלו',
    classesRemaining: 'שיעורים נותרו',
    upgradeSubscription: 'שדרג מנוי',
    registrationOpensIn: 'ההרשמה תפתח בעוד',
    nextWeek: 'השבוע הבא',
    thisWeek: 'השבוע הנוכחי',
    countdownDays: 'ימים',
    countdownHours: 'שעות',
    countdownMinutes: 'דקות',
    and: 'ו',
  },
  
  shop: {
    subscriptions: 'מנויים',
    selectPlan: 'בחר תוכנית',
    popular: 'פופולרי',
    month: 'חודש',
    cart: 'סל קניות',
    addToCart: 'הוסף לסל',
    removeFromCart: 'הסר מהסל',
    checkout: 'המשך לתשלום',
    total: 'סה"כ',
    empty: 'הסל ריק',
    features: 'מה כלול',
    perMonth: 'לחודש',
    plateBalance: 'יתרת פלטות',
    usePlates: 'השתמש בפלטות',
    discount: 'הנחה',
    finalPrice: 'מחיר סופי',
    originalPrice: 'מחיר מקורי',
    platesApplied: 'פלטות בשימוש',
    maxPlates: 'מקסימום',
    applyDiscount: 'הפעל הנחה',
    removeDiscount: 'בטל הנחה',
  },
  
  profile: {
    myProfile: 'הפרופיל שלי',
    editProfile: 'ערוך פרופיל',
    statistics: 'סטטיסטיקות',
    workoutHistory: 'היסטוריית אימונים',
    achievements: 'הישגים',
    settings: 'הגדרות',
    subscription: 'מנוי',
    paymentMethods: 'אמצעי תשלום',
    notifications: 'התראות',
    language: 'שפה',
    logout: 'התנתק',
    totalWorkouts: 'סך אימונים',
    totalMinutes: 'סך דקות',
    avgDuration: 'משך ממוצע',
    weeklyGoal: 'יעד שבועי',
  },
  
  workout: {
    logWorkout: 'רשום אימון',
    workoutType: 'סוג אימון',
    duration: 'משך',
    calories: 'קלוריות',
    exercises: 'תרגילים',
    addExercise: 'הוסף תרגיל',
    exerciseName: 'שם התרגיל',
    sets: 'סטים',
    reps: 'חזרות',
    weight: 'משקל',
    notes: 'הערות',
    save: 'שמור',
    cancel: 'בטל',
    delete: 'מחק',
    edit: 'ערוך',
    summary: 'סיכום אימון',
    heartRate: 'דופק',
    avg: 'ממוצע',
    max: 'מקסימום',
    distance: 'מרחק',
    km: 'ק"מ',
  },
  
  workoutTypes: {
    strength: 'כוח',
    cardio: 'אירובי',
    yoga: 'יוגה',
    hiit: 'HIIT',
    pilates: 'פילאטיס',
    boxing: 'אגרוף',
    dance: 'ריקוד',
    other: 'אחר',
  },
  
  admin: {
    dashboard: 'לוח בקרה',
    users: 'משתמשים',
    classes: 'שיעורים',
    subscriptions: 'מנויים',
    analytics: 'אנליטיקה',
    totalUsers: 'סך משתמשים',
    activeSubscriptions: 'מנויים פעילים',
    todayClasses: 'שיעורים היום',
    revenue: 'הכנסות',
    userDetails: 'פרטי משתמש',
    workoutHistory: 'היסטוריית אימונים',
    viewAll: 'צפה בהכל',
    edit: 'ערוך',
    delete: 'מחק',
    add: 'הוסף',
    search: 'חיפוש',
  },
  
  achievements: {
    firstWorkout: 'אימון ראשון',
    firstWorkoutDesc: 'השלם את האימון הראשון שלך',
    weekStreak: 'רצף שבועי',
    weekStreakDesc: 'אמן 7 ימים ברצף',
    monthStreak: 'רצף חודשי',
    monthStreakDesc: 'אמן 30 ימים ברצף',
    tenWorkouts: '10 אימונים',
    tenWorkoutsDesc: 'השלם 10 אימונים',
    fiftyWorkouts: '50 אימונים',
    fiftyWorkoutsDesc: 'השלם 50 אימונים',
    hundredWorkouts: '100 אימונים',
    hundredWorkoutsDesc: 'השלם 100 אימונים',
    earlyBird: 'ציפור מוקדמת',
    earlyBirdDesc: 'אמן לפני 7 בבוקר',
    nightOwl: 'ינשוף לילה',
    nightOwlDesc: 'אמן אחרי 10 בערב',
    classParticipant: 'משתתף שיעור',
    classParticipantDesc: 'השתתף ב-10 שיעורים',
  },
  
  common: {
    save: 'שמור',
    cancel: 'בטל',
    delete: 'מחק',
    edit: 'ערוך',
    add: 'הוסף',
    back: 'חזור',
    next: 'הבא',
    done: 'סיים',
    loading: 'טוען...',
    error: 'שגיאה',
    success: 'הצלחה',
    confirm: 'אשר',
    today: 'היום',
    week: 'שבוע',
    month: 'חודש',
    year: 'שנה',
    all: 'הכל',
  },
  
  payment: {
    cardNumber: 'מספר כרטיס',
    expiryDate: 'תוקף',
    cvv: 'CVV',
    cardholderName: 'שם בעל הכרטיס',
    billingAddress: 'כתובת לחיוב',
    payNow: 'שלם עכשיו',
    processing: 'מעבד תשלום...',
    success: 'התשלום בוצע בהצלחה',
    failed: 'התשלום נכשל',
    securePayment: 'תשלום מאובטח',
  },
};
