import { 
  User, 
  Class, 
  SubscriptionPackage, 
  Achievement,
  UserAchievement,
  Workout,
  HealthMetrics 
} from './types';

export const mockUser: User = {
  id: '1',
  name: 'דני כהן',
  email: 'danny@example.com',
  role: 'user',
  profileImage: 'https://i.pravatar.cc/150?img=12',
  subscription: {
    type: 'premium',
    status: 'active',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    classesPerMonth: 12,
    classesUsed: 5,
  },
  achievements: [],
  totalWorkouts: 24,
  weeklyGoal: 4,
  currentStreak: 7,
  plateBalance: 450,
};

export const mockCoach: User = {
  id: '2',
  name: 'שרה לוי',
  email: 'sarah@example.com',
  role: 'coach',
  profileImage: 'https://i.pravatar.cc/150?img=5',
  achievements: [],
  totalWorkouts: 0,
  weeklyGoal: 0,
  currentStreak: 0,
};

export const mockClasses: Class[] = [
  {
    id: '1',
    title: 'HIIT בוקר אנרגטי',
    description: 'אימון אינטנסיבי לשריפת קלוריות והגברת כושר',
    instructor: 'שרה לוי',
    instructorImage: 'https://i.pravatar.cc/150?img=5',
    date: '2025-11-04',
    time: '07:00',
    duration: 45,
    capacity: 20,
    enrolled: 12,
    type: 'hiit',
    difficulty: 'intermediate',
    location: 'אולם 1',
    requiredSubscription: ['basic', 'premium', 'vip'],
  },
  {
    id: '2',
    title: 'יוגה בשקיעה',
    description: 'יוגה מרגיעה לסיום היום',
    instructor: 'מיכל אברהם',
    instructorImage: 'https://i.pravatar.cc/150?img=9',
    date: '2025-11-04',
    time: '18:30',
    duration: 60,
    capacity: 15,
    enrolled: 8,
    type: 'yoga',
    difficulty: 'beginner',
    location: 'אולם 2',
    requiredSubscription: ['basic', 'premium', 'vip'],
  },
  {
    id: '3',
    title: 'אגרוף מתקדם',
    description: 'טכניקות אגרוף מתקדמות ואימון קרדיו',
    instructor: 'יוסי כהן',
    instructorImage: 'https://i.pravatar.cc/150?img=33',
    date: '2025-11-05',
    time: '19:00',
    duration: 50,
    capacity: 12,
    enrolled: 12,
    type: 'boxing',
    difficulty: 'advanced',
    location: 'אולם 3',
    requiredSubscription: ['premium', 'vip'],
  },
  {
    id: '4',
    title: 'פילאטיס בבוקר',
    description: 'חיזוק שרירי הליבה ושיפור הגמישות',
    instructor: 'רונית דוד',
    instructorImage: 'https://i.pravatar.cc/150?img=10',
    date: '2025-11-05',
    time: '08:00',
    duration: 55,
    capacity: 18,
    enrolled: 14,
    type: 'pilates',
    difficulty: 'intermediate',
    location: 'אולם 2',
    requiredSubscription: ['basic', 'premium', 'vip'],
  },
  {
    id: '5',
    title: 'כוח מלא',
    description: 'אימון כוח אינטנסיבי עם משקולות',
    instructor: 'אורי מזרחי',
    instructorImage: 'https://i.pravatar.cc/150?img=68',
    date: '2025-11-06',
    time: '17:00',
    duration: 60,
    capacity: 15,
    enrolled: 9,
    type: 'strength',
    difficulty: 'advanced',
    location: 'חדר כושר',
    requiredSubscription: ['premium', 'vip'],
  },
];

export const subscriptionPackages: SubscriptionPackage[] = [
  {
    id: '1',
    type: 'basic',
    name: 'בסיסי',
    price: 199,
    currency: '₪',
    duration: 'monthly',
    classesPerMonth: 8,
    features: [
      '8 שיעורים בחודש',
      'גישה לאפליקציה',
      'מעקב אימונים',
      'הישגים ואתגרים',
    ],
  },
  {
    id: '2',
    type: 'premium',
    name: 'פרימיום',
    price: 349,
    currency: '₪',
    duration: 'monthly',
    classesPerMonth: 12,
    popular: true,
    features: [
      '12 שיעורים בחודש',
      'גישה לכל השיעורים',
      'תוכנית אימונים אישית',
      'מעקב תזונה',
      'ייעוץ אישי חודשי',
      'אינטגרציה עם אפליקציות בריאות',
    ],
  },
  {
    id: '3',
    type: 'vip',
    name: 'VIP',
    price: 599,
    currency: '₪',
    duration: 'monthly',
    classesPerMonth: 20,
    features: [
      'שיעורים ללא הגבלה',
      'כל מה שכלול בפרימיום',
      'אימונים אישיים (2 בחודש)',
      'עדיפות בהרשמה לשיעורים',
      'גישה לאירועים מיוחדים',
      'ייעוץ תזונאי אישי',
      'מעקב מתקדם עם ניתוח ביצועים',
    ],
  },
];

export const mockAchievements: Achievement[] = [
  {
    id: '1',
    name: 'Just 100 workouts',
    name_hebrew: 'כולה 100 אימונים',
    icon: 'https://res.cloudinary.com/dtffqhujt/image/upload/v1759179882/19_olyugl.png',
    description: 'Attendance',
    description_hebrew: 'השתתפות ב- 100 אימונים',
    task_requirement: 100,
    points: 100,
    task_type: 'classes_attended',
    created_at: '2025-09-29T21:14:26.846Z',
    is_active: true,
  },
  {
    id: '2',
    name: "That's it? Only 200?",
    name_hebrew: 'זהו? רק 200?',
    icon: 'https://res.cloudinary.com/dtffqhujt/image/upload/v1759179905/17_kz7sh4.png',
    description: 'Attendance',
    description_hebrew: 'השתתפות ב-200 אימונים.',
    task_requirement: 200,
    points: 200,
    task_type: 'classes_attended',
    created_at: '2025-09-29T21:15:38.370Z',
    is_active: true,
  },
  {
    id: '3',
    name: '400 is good, but not enough',
    name_hebrew: '400 זה טוב, אבל לא מספיק.',
    icon: 'https://res.cloudinary.com/dtffqhujt/image/upload/v1759179881/18_y5acwv.png',
    description: 'Attendance',
    description_hebrew: 'השתתפות ב-400 אימונים.',
    task_requirement: 400,
    points: 400,
    task_type: 'classes_attended',
    created_at: '2025-09-29T21:17:21.260Z',
    is_active: true,
  },
  {
    id: '4',
    name: 'We are here for the experience?',
    name_hebrew: 'אנחנו כאן בשביל החוויה?',
    icon: 'https://res.cloudinary.com/dtffqhujt/image/upload/v1759179896/8_aw5q0o.png',
    description: 'Challenges',
    description_hebrew: 'לחוות את אימון ה-"1000 חזרות"',
    task_requirement: 1,
    points: 100,
    task_type: 'challenge',
    created_at: '2025-09-29T21:27:31.798Z',
    is_active: true,
  },
  {
    id: '5',
    name: "Rest day? Don't know it",
    name_hebrew: 'יום מנוחה? לא מכיר.',
    icon: 'https://res.cloudinary.com/dtffqhujt/image/upload/v1759179897/11_pddakv.png',
    description: 'Discipline',
    description_hebrew: '5 אימונים בשבוע - למשך שבועיים.',
    task_requirement: 1,
    points: 250,
    task_type: 'disapline',
    created_at: '2025-09-28T23:19:22.664Z',
    is_active: true,
  },
  {
    id: '6',
    name: "I'll just sleep here",
    name_hebrew: 'אני כבר אשאר לישון פה',
    icon: 'https://res.cloudinary.com/dtffqhujt/image/upload/v1759179899/13_zoq3sd.png',
    description: 'Discipline',
    description_hebrew: '5 אימונים בשבוע - למשך חודש.',
    task_requirement: 1,
    points: 600,
    task_type: 'disapline',
    created_at: '2025-09-28T23:25:21.635Z',
    is_active: true,
  },
  {
    id: '7',
    name: 'Boom, boom, crash',
    name_hebrew: 'בום, בום, טראח',
    icon: 'https://res.cloudinary.com/dtffqhujt/image/upload/v1759179882/20_vpgvfo.png',
    description: 'Challenges',
    description_hebrew: 'ביצוע 50 הטחות - בדקה.',
    task_requirement: 1,
    points: 200,
    task_type: 'challenge',
    created_at: '2025-09-29T21:21:45.417Z',
    is_active: true,
  },
  {
    id: '8',
    name: "I'm in with you on rent",
    name_hebrew: 'אני נכנס איתך בשכירות',
    icon: 'https://res.cloudinary.com/dtffqhujt/image/upload/v1759179902/12_dqwyuf.png',
    description: 'Discipline',
    description_hebrew: '5 אימונים בשבוע - למשך שלושה חודשים.',
    task_requirement: 1,
    points: 2000,
    task_type: 'disapline',
    created_at: '2025-09-29T21:29:48.135Z',
    is_active: true,
  },
];

export const mockUserAchievements: UserAchievement[] = [
  {
    id: '1',
    achievement: mockAchievements[0],
    progress: 100,
    completed: true,
    dateEarned: '2025-10-01',
  },
  {
    id: '2',
    achievement: mockAchievements[1],
    progress: 150,
    completed: false,
  },
  {
    id: '3',
    achievement: mockAchievements[3],
    progress: 1,
    completed: true,
    dateEarned: '2025-10-15',
  },
  {
    id: '4',
    achievement: mockAchievements[4],
    progress: 0,
    completed: false,
  },
];

export const mockWorkouts: Workout[] = [
  {
    id: '1',
    userId: '1',
    title: 'אימון בוקר',
    date: '2025-11-03',
    duration: 45,
    calories: 350,
    type: 'strength',
    heartRateAvg: 135,
    heartRateMax: 165,
    exercises: [
      { id: '1', name: 'סקוואט', sets: 4, reps: 12, weight: 60 },
      { id: '2', name: 'בנץ\' פרס', sets: 4, reps: 10, weight: 50 },
      { id: '3', name: 'משיכות', sets: 3, reps: 8, weight: 40 },
    ],
  },
  {
    id: '2',
    userId: '1',
    title: 'ריצה בפארק',
    date: '2025-11-02',
    duration: 30,
    calories: 280,
    type: 'cardio',
    heartRateAvg: 142,
    heartRateMax: 175,
    distance: 5.2,
    exercises: [],
  },
];

export const mockHealthMetrics: HealthMetrics[] = [
  {
    date: '2025-11-03',
    steps: 8542,
    activeMinutes: 45,
    calories: 2340,
    distance: 6.2,
    heartRateResting: 62,
    sleep: 7.5,
  },
  {
    date: '2025-11-02',
    steps: 10234,
    activeMinutes: 60,
    calories: 2580,
    distance: 7.8,
    heartRateResting: 60,
    sleep: 8.0,
  },
];

export const mockUsers: User[] = [
  mockUser,
  {
    id: '3',
    name: 'מיכל רוזנברג',
    email: 'michal@example.com',
    role: 'user',
    profileImage: 'https://i.pravatar.cc/150?img=20',
    subscription: {
      type: 'basic',
      status: 'active',
      startDate: '2025-10-01',
      endDate: '2025-11-01',
      classesPerMonth: 8,
      classesUsed: 6,
    },
    achievements: mockAchievements,
    totalWorkouts: 15,
    weeklyGoal: 3,
    currentStreak: 3,
    plateBalance: 120,
  },
  {
    id: '4',
    name: 'יוסי אברהם',
    email: 'yossi@example.com',
    role: 'user',
    profileImage: 'https://i.pravatar.cc/150?img=52',
    subscription: {
      type: 'vip',
      status: 'active',
      startDate: '2025-09-01',
      endDate: '2025-12-01',
      classesPerMonth: 20,
      classesUsed: 12,
    },
    achievements: mockAchievements,
    totalWorkouts: 42,
    weeklyGoal: 5,
    currentStreak: 14,
    plateBalance: 850,
  },
];
