export const Colors = {
  light: {
    background: '#FFFFFF',
    foreground: '#09090B',
    card: '#FFFFFF',
    cardForeground: '#09090B',
    popover: '#FFFFFF',
    popoverForeground: '#09090B',
    primary: '#D14D72',
    primaryForeground: '#FFFFFF',
    secondary: '#F4F4F5',
    secondaryForeground: '#09090B',
    muted: '#F4F4F5',
    mutedForeground: '#71717A',
    accent: '#F4F4F5',
    accentForeground: '#09090B',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#E4E4E7',
    input: '#E4E4E7',
    ring: '#D14D72',
  },
  dark: {
    background: '#09090B',
    foreground: '#FAFAFA',
    card: '#09090B',
    cardForeground: '#FAFAFA',
    popover: '#09090B',
    popoverForeground: '#FAFAFA',
    primary: '#D14D72',
    primaryForeground: '#FFFFFF',
    secondary: '#27272A',
    secondaryForeground: '#FAFAFA',
    muted: '#27272A',
    mutedForeground: '#A1A1AA',
    accent: '#27272A',
    accentForeground: '#FAFAFA',
    destructive: '#EF4444',
    destructiveForeground: '#FAFAFA',
    border: '#27272A',
    input: '#27272A',
    ring: '#D14D72',
  },
};
